# Generated by Django 3.2.7 on 2021-09-27 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dndPlayerClass', '0002_auto_20210927_1634'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='languages',
            table='player_class_languages',
        ),
    ]
