# Generated by Django 3.2.7 on 2021-09-28 09:28

import django.contrib.postgres.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dndPlayerClass', '0003_alter_languages_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'player_class_features',
            },
        ),
        migrations.AlterField(
            model_name='languages',
            name='given_languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, size=None),
        ),
        migrations.AddField(
            model_name='playerclass',
            name='featureIDs',
            field=models.ManyToManyField(to='dndPlayerClass.Features'),
        ),
    ]
