# Generated by Django 3.2.7 on 2021-09-27 14:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerClass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('hit_die_sides', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'player_class',
            },
        ),
    ]
