# Generated by Django 3.2.7 on 2021-09-28 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dndPlayerClassBlueprint', '0004_auto_20210928_1128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerclass',
            old_name='featureIDs',
            new_name='features_junction',
        ),
    ]
