# Generated by Django 3.2.7 on 2021-09-28 14:45

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dndPlayerClassBlueprint', '0005_rename_featureids_playerclass_features_junction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Magic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('damage', models.CharField(max_length=255, null=True)),
                ('cast_at_will', models.BooleanField(default=False)),
                ('components', models.JSONField()),
                ('arcaneFocusReplacesComponents', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'player_class_spellcasting_magic',
            },
        ),
        migrations.CreateModel(
            name='Spellcasting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('additional_spells', models.PositiveIntegerField()),
                ('additional_cantrips', models.PositiveIntegerField()),
                ('spell_slots', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), size=9)),
                ('spells_prepared', models.PositiveIntegerField(null=True)),
                ('languagesID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dndPlayerClassBlueprint.magic')),
            ],
            options={
                'db_table': 'player_class_spellcasting',
            },
        ),
        migrations.AddField(
            model_name='playerclass',
            name='spellcastingID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dndPlayerClassBlueprint.spellcasting'),
        ),
    ]
