# Generated by Django 3.2.7 on 2021-09-28 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dndPlayerClassBlueprint', '0006_auto_20210928_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magic',
            name='cast_at_will',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
