# Generated by Django 3.2.7 on 2021-09-29 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dndPlayerClassBlueprint', '0008_alter_magic_arcanefocusreplacescomponents'),
    ]

    operations = [
        migrations.AddField(
            model_name='magic',
            name='healing',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='magic',
            name='arcaneFocusReplacesComponents',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='magic',
            name='cast_at_will',
            field=models.BooleanField(default=False),
        ),
    ]
