# Generated by Django 3.2.7 on 2021-09-29 10:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dndPlayerClassBlueprint', '0015_alter_spellcasting_spell_slots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spellcasting',
            name='spell_slots',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), size=2),
        ),
    ]
