# Generated by Django 3.2.7 on 2021-10-04 09:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dndPlayerClassBlueprint', '0017_auto_20211004_0954'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spellcasting',
            old_name='languagesID',
            new_name='given_magic',
        ),
        migrations.AlterField(
            model_name='spellcasting',
            name='spell_slots',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), size=9),
        ),
    ]
