# Generated by Django 3.2.7 on 2021-10-04 09:43

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dndPlayerClassBlueprint', '0018_auto_20211004_1111'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proficiencies',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('proficiency_bonus', models.PositiveIntegerField()),
                ('proficient_saving_throws', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('STR', 'Strength'), ('DEX', 'Dexterity'), ('CON', 'Constitution'), ('INT', 'Intelligence'), ('WIS', 'Wisdom'), ('CHA', 'Charisma')], max_length=255, null=True), size=None)),
                ('additional_proficient_saving_throws', models.PositiveIntegerField()),
                ('proficient_skills', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('STR', 'Strength'), ('DEX', 'Dexterity'), ('CON', 'Constitution'), ('INT', 'Intelligence'), ('WIS', 'Wisdom'), ('CHA', 'Charisma')], max_length=255), null=True, size=None)),
                ('additional_proficient_skills', models.PositiveIntegerField()),
                ('weapon_proficiencies', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None)),
            ],
            options={
                'db_table': 'player_class_proficiencies',
            },
        ),
        migrations.AddField(
            model_name='playerclass',
            name='proficiencies_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dndPlayerClassBlueprint.proficiencies'),
        ),
    ]
