# Generated by Django 3.2.7 on 2021-10-04 09:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dndPlayerClassBlueprint', '0019_auto_20211004_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proficiencies',
            name='proficient_skills',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('ATHLETICS', 'Athletics'), ('ACROBATICS', 'Acrobatics'), ('SLEIGHT_OF_HAND', 'Sleight of Hand'), ('STEALTH', 'Stealth'), ('ARCANA', 'Arcana'), ('HISTORY', 'History'), ('INVESTIGATION', 'Investigation'), ('NATURE', 'Nature'), ('RELIGION', 'Religion'), ('ANIMAL_HANDLING', 'Animal Handling'), ('INSIGHT', 'Insight'), ('MEDICINE', 'Medicine'), ('PERCEPTION', 'Perception'), ('SURVIVAL', 'Survival'), ('DECEPTION', 'Deception'), ('INTIMIDATION', 'Intimidation'), ('PERFORMANCE', 'Performance'), ('PERSUASION', 'Persuasion')], max_length=255), null=True, size=None),
        ),
    ]
