# Generated by Django 3.2.7 on 2021-10-04 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dndPlayerClassBlueprint', '0020_alter_proficiencies_proficient_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerclass',
            name='features_junction',
        ),
        migrations.AddField(
            model_name='playerclass',
            name='player_class_features_junction',
            field=models.ManyToManyField(null=True, to='dndPlayerClassBlueprint.Features'),
        ),
    ]
