# Generated by Django 3.2.7 on 2021-10-04 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dndPlayerClassBlueprint', '0021_auto_20211004_1619'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerclass',
            old_name='player_class_features_junction',
            new_name='features_junction',
        ),
    ]
