# Generated by Django 3.2.7 on 2021-11-17 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dndPlayerClassBlueprint', '0022_rename_player_class_features_junction_playerclass_features_junction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerclass',
            old_name='proficiencies_id',
            new_name='proficienciesID',
        ),
    ]
